#!/usr/bin/env python3
"""
Translate Localizable.xcstrings to Simplified Chinese (zh-Hans).
Removes German (de) localization entries and adds Chinese translations.
"""

import json
import os

# Comprehensive translation dictionary: English -> Simplified Chinese
TRANSLATIONS = {
    # Empty key / special strings
    "": "",
    "- %@": "- %@",
    "(%@)": "(%@)",
    "(%lld)": "(%lld)",

    # Time/size suffixes
    "%lldh %lldm": "%lld小时 %lld分钟",
    "%lldm": "%lld分钟",
    "%lld%%": "%lld%%",
    "1:23": "1:23",
    "just_now": "刚刚",
    "yesterday": "昨天",
    "today": "今天",
    "entries": "条目",
    "words": "词",
    "total": "总计",
    "or": "或",
    "e.g.": "例如",
    "e.g. addr": "例如 addr",
    "e.g. github.com": "例如 github.com",
    "e.g. kubernetees": "例如 kubernetees",
    "e.g. Kubernetes": "例如 Kubernetes",
    "e.g. Make Formal": "例如 正式化",
    "M4A": "M4A",
    "WAV": "WAV",
    "HTML": "HTML",
    "Code": "代码",
    "SRT": "SRT",
    "VTT": "VTT",
    "OK": "确定",
    "None": "无",
    "Aa": "Aa",
    "None": "无",

    # Ready / status
    "%@ ready": "%@ 就绪",
    "not ready": "未就绪",
    "Ready": "就绪",
    "Ready to start dictating?": "准备好开始听写了吗？",
    "Idle": "空闲",
    "Pending": "等待中",
    "Error": "错误",
    "Error - %@": "错误 - %@",
    "Error: %@": "错误：%@",
    "Recording...": "录音中...",
    "Recording": "录音",
    "Recording started": "录音已开始",
    "Transcribing...": "转录中...",
    "Transcribing": "转录中",
    "Processing...": "处理中...",
    "Processing": "处理中",
    "Processed": "已处理",
    "Processing transcription": "正在转录",
    "Processing prompt: %@": "正在处理提示词：%@",
    "Processing prompt": "正在处理提示词",
    "Prompt complete": "提示词完成",
    "Downloading %@": "正在下载 %@",
    "Installing...": "安装中...",
    "Installing plugins...": "正在安装插件...",
    "Loading...": "加载中...",
    "Loading": "加载中",
    "Loading plugins...": "正在加载插件...",
    "Loading community packs...": "正在加载社区包...",
    "Cancelled": "已取消",
    "Retry": "重试",
    "Try Again": "重试",
    "Stop Preview": "停止预览",

    # Duration / time strings
    "%lld days ago": "%lld 天前",
    "%lld hr ago": "%lld 小时前",
    "%lld min ago": "%lld 分钟前",
    "30 days": "30 天",
    "60 days": "60 天",
    "90 days": "90 天",
    "180 days": "180 天",
    "Last 7 Days": "最近 7 天",
    "Last 30 Days": "最近 30 天",
    "Last 90 Days": "最近 90 天",
    "Last Month": "上月",
    "This Week": "本周",
    "Today": "今天",
    "Yesterday": "昨天",
    "Older": "更早",
    "All Time": "全部时间",
    "Date": "日期",
    "Time": "时间",
    "Month": "月份",
    "Week": "周",
    "Day": "天",

    # Record-related strings
    "recorder.delete": "删除",
    "recorder.duration": "时长",
    "recorder.format": "输出格式",
    "recorder.trackMode": "轨道模式",
    "recorder.mic": "麦克风",
    "recorder.noRecordings": "暂无录音",
    "recorder.recordings": "录音列表",
    "recorder.revealInFinder": "在 Finder 中显示",
    "recorder.sources": "音频源",
    "recorder.startRecording": "开始录音",
    "recorder.stopRecording": "停止录音",
    "recorder.systemAudio": "系统音频",
    "recorder.systemAudioPermission": "系统音频录制需要屏幕录制权限。",
    "recorder.transcribe": "转录",
    "recorder.transcribing": "转录中...",
    "recorder.liveTranscript": "实时转录",
    "recorder.liveTranscription": "实时转录",
    "recorder.transcription": "转录",
    "recorder.liveTranscriptActive": "实时转录窗口已激活",
    "recorder.liveTranscriptHint": "从集成安装实时转录插件以获得实时转录窗口。",
    "recorder.noEngine": "未选择引擎",
    "recorder.language": "语言",
    "recorder.hasTranscript": "转录文本",
    "recorder.showTranscript": "显示转录",
    "recorder.copyTranscript": "复制转录",
    "settings.showRecorderTab": "显示录音标签页",
    "settings.showRecorderTab.description": "显示录音标签页，用于录制麦克风和系统音频。",

    # Track mode
    "trackMode.mixed": "混合",
    "trackMode.separate": "分离（麦克风左/系统右）",

    # Watch folder
    "settings.tab.watchFolder": "监视文件夹",
    "watchFolder.folders": "文件夹",
    "watchFolder.watchFolder": "监视文件夹",
    "watchFolder.noFolder": "未选择文件夹",
    "watchFolder.selectFolder": "选择文件夹...",
    "watchFolder.selectFolder.message": "选择要监视音频文件的文件夹",
    "watchFolder.selectOutputFolder.message": "选择转录文本的输出文件夹",
    "watchFolder.outputFolder": "输出文件夹",
    "watchFolder.outputFolder.sameAsWatch": "与监视文件夹相同",
    "watchFolder.settings": "设置",
    "watchFolder.engine": "引擎",
    "watchFolder.engine.default": "默认（全局选择）",
    "watchFolder.model.default": "默认模型",
    "watchFolder.outputFormat": "输出格式",
    "watchFolder.plainText": "纯文本 (.txt)",
    "watchFolder.deleteSource": "转录后删除源文件",
    "watchFolder.autoStart": "应用启动时开始监视",
    "watchFolder.startWatching": "开始监视",
    "watchFolder.stopWatching": "停止监视",
    "watchFolder.history": "处理历史",
    "watchFolder.history.empty": "尚无处理的文件。",
    "watchFolder.history.clear": "清除历史",
    "watchFolder.language": "语言",
    "watchFolder.language.auto": "自动检测",
    "watchFolder.description": "监视所选文件夹中的新音频文件并自动转录。",

    # Prompts presets
    "preset.actionItems": "提取任务",
    "preset.createTable": "创建表格",
    "preset.draftEmail": "起草邮件",
    "preset.formatAsList": "格式化为列表",
    "preset.jsonData": "JSON 数据",
    "preset.meetingNotes": "会议记录",
    "preset.reply": "回复",
    "preset.translate": "翻译",
    "preset.writeEmail": "写邮件",

    # File transcription
    "fileTranscription.transcription": "转录",

    # General UI
    "About": "关于",
    "Accessibility": "辅助功能",
    "Accessibility access is required to paste text into other apps.": "需要辅助功能权限才能将文本粘贴到其他应用中。",
    "Accessibility access required": "需要辅助功能权限",
    "Action Target": "操作目标",
    "Actions": "操作",
    "Active Screen": "活动屏幕",
    "Activity": "活动",
    "Add": "添加",
    "Add Correction": "添加纠正",
    "Add Files...": "添加文件...",
    "Add new prompt": "添加新提示词",
    "Add new snippet": "添加新代码片段",
    "Add Profile": "添加配置文件",
    "Add Prompt": "添加提示词",
    "Add Snippet": "添加代码片段",
    "Add Term": "添加术语",
    "Advanced": "高级",
    "After 1 hour": "1 小时后",
    "After 2 minutes": "2 分钟后",
    "After 5 minutes": "5 分钟后",
    "After 10 minutes": "10 分钟后",
    "After 30 minutes": "30 分钟后",
    "All": "全部",
    "All Apps": "全部应用",
    "All available plugins are already installed.": "所有可用的插件都已安装。",
    "Always visible": "始终可见",
    "API key configured": "API 密钥已配置",
    "API key required - configure in Integrations tab": "需要 API 密钥 - 请在集成标签页中配置",
    "API key required": "需要 API 密钥",
    "API Server": "API 服务器",
    "App Language": "应用语言",
    "Appearance": "外观",
    "Apps": "应用",
    "Apps Used": "使用的应用",
    "Are you sure you want to uninstall %@? This will remove the plugin and its data.": "确定要卸载 %@ 吗？这将删除插件及其数据。",
    "Assign a hotkey to always use this profile, regardless of the active app.": "分配一个快捷键以始终使用此配置文件，无论当前应用是什么。",
    "Audio": "音频",
    "Audio Ducking": "音频避让",
    "Auto-delete after": "自动删除于",
    "Auto-detect": "自动检测",
    "Auto-unload model": "自动卸载模型",
    "Automatically extracts facts, preferences and patterns from your transcriptions using an LLM. Memories are injected into prompt context.": "使用 LLM 自动从转录文本中提取事实、偏好和模式。记忆会被注入到提示词上下文中。",
    "Automatically unloads local models from memory after inactivity. It reloads when needed. Does not affect cloud engines.": "在空闲后自动将本地模型从内存中卸载。需要时会重新加载。不影响云端引擎。",
    "Available": "可用",
    "Available Plugins": "可用插件",
    "Avg. WPM": "平均每分钟词数",

    # Button labels
    "Back": "返回",
    "Bottom": "底部",
    "Browse Term Packs": "浏览术语包",
    "Browse the Available tab or install from file.": '浏览"可用"标签页或从文件安装。',
    "Built-in": "内置",
    "Built-in Display": "内置显示器",
    "Cancel": "取消",
    "Case sensitive": "区分大小写",
    "Check for Updates...": "检查更新...",
    "Daily": "每日",
    "Daily includes stable, release candidate, and daily builds.": "每日版包含稳定版、候选发布版和每日构建版。",
    "Check status:": "检查状态：",
    "Choose a transcription engine. Each engine needs to download a model before it can be used. Open settings to configure.": "选择转录引擎。每个引擎需要下载模型才能使用。打开设置进行配置。",
    "Choose Apps": "选择应用",
    "Choose Apps...": "选择应用...",
    "Choose Files...": "选择文件...",
    "Choose how to trigger dictation.": "选择如何触发听写。",
    "Choose how you want to trigger dictation, then record a shortcut.": "选择您想要触发听写的方式，然后录制快捷键。",
    "Clear All": "清除全部",
    "Clear All Data": "清除所有数据",
    "Clear All Memories": "清除所有记忆",
    "Clear All Memories?": "确定清除所有记忆？",
    "Clear Filters": "清除筛选",
    "Clear search": "清除搜索",
    "Clear shortcut": "清除快捷键",
    "Click the text field below, then press your hotkey and say something!": "点击下方的文本字段，然后按快捷键并说话！",
    "Click to insert": "点击插入",
    "Click to insert a placeholder:": "点击插入占位符：",
    "Clipboard": "剪贴板",
    "Clipboard content": "剪贴板内容",
    "Cloud": "云端",
    "Cloud-based transcription. Requires a free API key.": "基于云端的转录。需要免费 API 密钥。",
    "Command Line Tool": "命令行工具",
    "Copied to clipboard": "已复制到剪贴板",
    "Copy": "复制",
    "Copy All Text": "复制全部文本",
    "Correct Text": "正确文本",
    "Community Packs": "社区包",
    "Correction": "纠正",
    "Corrections": "纠正",
    "Corrections added to dictionary": "纠正已添加到词典",
    "Corrections replace text after transcription": "转录后替换文本",
    "Create profiles to use app-specific transcription settings.": "创建配置文件以使用应用特定的转录设置。",
    "Create prompts to process your dictated text with AI": "创建提示词以使用 AI 处理听写文本",
    "Create snippets to automatically expand short triggers into longer text": "创建代码片段以自动将短触发器扩展为更长文本",
    "Dashboard": "仪表盘",
    "Default": "默认",
    "Default Engine": "默认引擎",
    "Default LLM Provider": "默认 LLM 提供商",
    "Default LLM": "默认 LLM",
    "Delete": "删除",
    "Delete %lld entries": "删除 %lld 条目",
    "Delete %lld entries matching current filters?": "删除符合当前筛选条件的 %lld 条目？",
    "Delete all %lld entries? This cannot be undone.": "删除全部 %lld 条目？此操作无法撤销。",
    "Delete All Visible": "删除所有可见项",
    "Delete Entries": "删除条目",
    "Delete %@": "删除 %@",
    "Deutsch": "德语",
    "Dictated text will appear here.": "听写的文本将显示在这里。",
    "Dictation shortcut": "听写快捷键",
    "Dictionary": "词典",
    "Display": "显示",
    "Done": "完成",
    "Drop audio or video files here": "将音频或视频文件拖放到此处",
    "Dynamic Placeholders": "动态占位符",

    "Edit": "编辑",
    "Edit Correction": "编辑纠正",
    "Edit Profile": "编辑配置文件",
    "Edit Prompt": "编辑提示词",
    "Edit Snippet": "编辑代码片段",
    "Edit Term": "编辑术语",
    "Edit %@": "编辑 %@",
    "Enable API Server": "启用 API 服务器",
    "Enable Memory": "启用记忆",
    "Enable translation": "启用翻译",
    "Enable %@": "启用 %@",
    "Enable in System Settings": "在系统设置中启用",
    "Engine": "引擎",
    "English": "英语",
    "Enhance": "增强",
    "Export %lld entries as...": "导出 %lld 条目为...",
    "Export All": "导出全部",
    "Export All as SRT": "导出全部为 SRT",
    "Export All as VTT": "导出全部为 VTT",
    "Export as...": "导出为...",
    "Export...": "导出...",
    "Export Here": "导出到这里",
    "Export Subtitles": "导出字幕",
    "Extraction Model": "提取模型",
    "Extraction Prompt": "提取提示词",
    "Extraction Provider": "提取提供商",
    "Failed to load community packs.": "加载社区包失败。",
    "Failed to load plugins.": "加载插件失败。",
    "Fast, private speech-to-text for your Mac. Transcribe with local or cloud engines, process text with AI prompts, and insert directly into any app.": "为您的 Mac 提供快速、私密的语音转文字服务。使用本地或云端引擎转录，使用 AI 提示词处理文本，并直接插入到任何应用中。",
    "Fastest": "最快",
    "Fast cloud AI. Also supports transcription. Requires a free API key.": "快速云端 AI。也支持转录。需要免费 API 密钥。",
    "File Transcription": "文件转录",
    "Finish": "完成",
    "General": "通用",
    "Get Started": "开始使用",
    "Global Setting": "全局设置",
    "Go to Dashboard": "前往仪表盘",
    "Grant Access": "授予访问权限",
    "Granted": "已授权",
    "Go to Integrations": "前往集成",
    "Groq is already installed and also works as an LLM provider.": "Groq 已安装，也可用作 LLM 提供商。",
    "Free API Key": "免费 API 密钥",
    "Already Installed": "已安装",
    "Also Available": "也可使用",
    "Also Installed": "也已安装",

    "Hello, this is a live preview of the streaming text...": "您好，这是实时流式文本的预览...",
    "Helps Whisper recognize technical terms": "帮助 Whisper 识别技术术语",
    "Higher priority profiles take precedence when multiple profiles match.": "当多个配置文件匹配时，优先级更高的配置文件优先。",
    "History": "历史记录",
    "Hold to record, release to stop.": "按住录音，松开停止。",
    "Home": "首页",
    "Hotkey": "快捷键",
    "Hotkeys": "快捷键",
    "Hybrid": "混合",
    "I'll try later": "稍后尝试",
    "Icon": "图标",
    "Immediate": "立即",
    "Import...": "导入...",
    "Import Complete": "导入完成",
    "Import Dictionary...": "导入词典...",
    "Import All": "导入全部",
    "Import Preset": "导入预设",
    "Import Presets": "导入预设",
    "All presets imported": "所有预设已导入",
    "All imported": "全部已导入",
    "Load Presets": "加载预设",
    "in any app to begin.": "在任何应用中开始。",
    "Indicator": "指示器",
    "Input Device": "输入设备",
    "Insert Text": "插入文本",
    "Install": "安装",
    "Install a transcription engine to get started.": "安装转录引擎以开始使用。",
    "Install a transcription engine to get started. Each engine needs to download a model before it can be used.": "安装转录引擎以开始使用。每个引擎需要下载模型才能使用。",
    "Install additional LLM providers from the Integrations tab.": "从集成标签页安装额外的 LLM 提供商。",
    "Install Command Line Tool": "安装命令行工具",
    "Install Failed": "安装失败",
    "Install from File...": "从文件安装...",
    "Installed": "已安装",
    "Installed at /usr/local/bin/davywhisper": "已安装于 /usr/local/bin/davywhisper",
    "Installing...": "安装中...",
    "Install %@": "安装 %@",
    "Install an LLM provider plugin (e.g. Groq, OpenAI) to use prompts.": "安装 LLM 提供商插件（例如 Groq、OpenAI）以使用提示词。",
    "Instead of inserting the LLM result as text, send it to an action plugin.": "不将 LLM 结果作为文本插入，而是发送到操作插件。",
    "Integrations": "集成",
    "JSON (.json)": "JSON (.json)",
    "JSON output:": "JSON 输出：",

    "Language": "语言",
    "Later": "稍后",
    "Launch at Login": "登录时启动",
    "Learn More": "了解更多",
    "Left Side": "左侧",
    "Licensed under the GNU General Public License v3.0": "根据 GNU 通用公共许可证 v3.0 授权",
    "List models:": "模型列表：",
    "LLM Provider": "LLM 提供商",
    "LLM Providers": "LLM 提供商",
    "LLM:": "LLM：",
    "Local": "本地",
    "Markdown (.md)": "Markdown (.md)",
    "Memory": "记忆",
    "Menu bar icon hidden": "菜单栏图标已隐藏",
    "Microphone": "麦克风",
    "Microphone access is required for dictation.": "听写需要麦克风权限。",
    "Microphone access is required to continue.": "需要麦克风权限才能继续。",
    "Microphone access required": "需要麦克风权限",
    "Microphone disconnected": "麦克风已断开",
    "Microphone disconnected. Falling back to system default.": "麦克风已断开。回退到系统默认设置。",
    "Min. text length:": "最小文本长度：",
    "Model": "模型",
    "Name": "名称",
    "Name and prompt cannot be empty": "名称和提示词不能为空",
    "Never": "从不",
    "New Correction": "新建纠正",
    "New Profile": "新建配置文件",
    "New Prompt": "新建提示词",
    "New Snippet": "新建代码片段",
    "New Term": "新建术语",
    "Next": "下一步",
    "No activity in this period.": "此时段无活动。",
    "No apps assigned": "未分配应用",
    "No community packs available yet.": "暂无社区包可用。",
    "No dictionary entries": "无词典条目",
    "No Entries": "无条目",
    "No entries for this filter": "此筛选条件无条目",
    "No hotkey is configured. Go back to set one up.": "未配置快捷键。返回进行设置。",
    "No hotkey set. You won't be able to start dictation without one.": "未设置快捷键。没有快捷键将无法开始听写。",
    "No matching prompts": "无匹配的提示词",
    "No memory storage plugins active. Enable one in Integrations.": "没有活动的记忆存储插件。在集成中启用一个。",
    "No model loaded": "未加载模型",
    "No plugins installed.": "未安装插件。",
    "No Profiles": "无配置文件",
    "No prompts yet": "暂无提示词",
    "No results for the active filters.": "活动筛选条件无结果。",
    "No snippets yet": "暂无代码片段",
    "No speech detected": "未检测到语音",
    "No speech recognized": "无法识别语音",
    "Too short, hold the hotkey a bit longer": "时间太短，请按住快捷键久一点",
    "No transcription engine is ready. Go back to set one up.": "没有转录引擎就绪。返回进行设置。",
    "No transcription engines available.": "无转录引擎可用。",
    "No transcription engines installed. Install engines via Integrations.": "未安装转录引擎。通过集成安装引擎。",
    "No transcriptions yet.": "暂无转录。",
    "No URL patterns": "无 URL 模式",
    "noLLMProvider": "未配置 LLM 提供商。请在设置中设置 Apple Intelligence 或 API 密钥。",
    "Not available - Apple Intelligence must be enabled in System Settings": "不可用 - 必须在系统设置中启用 Apple Intelligence",
    "Not configured": "未配置",
    "Not installed": "未安装",
    "Not running": "未运行",
    "Notch": "刘海",

    "Older entries are automatically removed at app launch.": "较旧的条目会在应用启动时自动删除。",
    "Only during activity": "仅在活动期间",
    "On-device AI processing. No API key needed.": "设备端 AI 处理。无需 API 密钥。",
    "Original": "原文",
    "Open an engine's settings to download a model.": "打开引擎设置以下载模型。",
    "Open in Raycast": "在 Raycast 中打开",
    "Open Integrations": "打开集成",
    "Open Plugins Folder": "打开插件文件夹",
    "Original text cannot be empty": "原文不能为空",
    "Overlay": "悬浮层",
    "Override the default provider for this prompt. Leave on \"Default\" to use the global setting.": '覆盖此提示词的默认提供商。保持"默认"以使用全局设置。',
    "Overrides": "覆盖",

    "Palette shortcut": "面板快捷键",
    "Percentage of your current volume to use during recording. 0% mutes completely.": "录音时使用当前音量的百分比。0% 完全静音。",
    "Permissions": "权限",
    "Pipe to clipboard:": "输出到剪贴板：",
    "Plain Text (.txt)": "纯文本 (.txt)",
    "Plain Text": "纯文本",
    "Play sound feedback": "播放声音反馈",
    "Plays a sound when recording starts and when transcription completes.": "录音开始和转录完成时播放声音。",
    "Plugin incompatible with this macOS version": "插件与此 macOS 版本不兼容",
    "Plugins": "插件",
    "Position": "位置",
    "Post-Processors": "后处理器",
    "Pre-built collections of technical terms for common domains": "常见领域技术术语的预建集合",
    "Preserve clipboard content": "保留剪贴板内容",
    "Press": "按",
    "Press %@ in any app to get started.": "在任何应用中按 %@ 开始使用。",
    "Press a hotkey and talk naturally in any app.": "在任何应用中按快捷键并自然说话。",
    "Press a key…": "按一个键…",
    "tap again for double-tap…": "再次按以实现双击…",
    "Press to start, press again to stop.": "按开始，再次按停止。",
    "Primary Screen": "主屏幕",
    "Priority": "优先级",
    "Profile": "配置文件",
    "Profile name": "配置文件名称",
    "Profile shortcut": "配置文件快捷键",
    "Profiles": "配置文件",
    "Prompt": "提示词",
    "Prompt Palette": "提示词面板",
    "Prompts": "提示词",
    "Prompts & AI": "提示词与 AI",
    "Process your dictated text with AI - translate, reformat, summarize, and more.": "使用 AI 处理您的听写文本 - 翻译、重新格式化、总结等。",
    "Prompt Presets": "提示词预设",
    "Built-in prompts for common tasks like translation, email drafting, and formatting.": "用于翻译、邮件起草和格式化等常见任务的内置提示词。",
    "You have an LLM provider ready.": "您已有一个 LLM 提供商就绪。",
    "Provider": "提供商",
    "Push-to-Talk": "按键说话",
    "Quit": "退出",

    "Raycast Extension": "Raycast 扩展",
    "Read Back Last Transcription": "朗读上次转录",
    "Recent Transcriptions": "最近转录",
    "Recommended": "推荐",
    "Recommended for pasting text into other apps. You can grant this later.": "推荐用于将文本粘贴到其他应用。您可以稍后授予此权限。",
    "Record Shortcut": "录制快捷键",
    "Recording Indicator": "录音指示器",
    "Recording timer": "录音计时器",
    "Recording shortcut - press a key or Escape to cancel": "录制快捷键 - 按一个键或 Escape 取消",
    "Record shortcut for %@": "为 %@ 录制快捷键",
    "Reduce system volume during recording": "录音时降低系统音量",
    "Replacement": "替换文本",
    "Replacement text cannot be empty for corrections": "纠正的替换文本不能为空",
    "Replaces incorrect transcriptions": "替换错误的转录文本",
    "Required": "必需",
    "Requires the API server to be running.": "需要 API 服务器正在运行。",
    "Requires the API server to be running. The CLI tool connects to DavyWhisper's API for fast transcription without model cold starts.": "需要 API 服务器正在运行。CLI 工具连接到 DavyWhisper 的 API 以实现快速转录，无需模型冷启动。",
    "Reset to Default": "重置为默认",
    "Release Candidate": "候选发布版",
    "Release Candidate includes stable and preview builds.": "候选发布版包含稳定版和预览版。",
    "Restart Now": "立即重启",
    "Restart Required": "需要重启",
    "Restores your clipboard after text insertion. Without this, your clipboard contains the transcribed text after dictation.": "文本插入后恢复剪贴板。没有此选项，听写后剪贴板将包含转录文本。",
    "Right Side": "右侧",
    "Right-click to export or delete selected entries.": "右键点击以导出或删除所选条目。",
    "Run setup again": "重新运行设置",
    "Running on port %@": "运行于端口 %@",
    "Runs locally on your Mac. No API key needed.": "在您的 Mac 上本地运行。无需 API 密钥。",

    "Save": "保存",
    "Save audio with transcriptions": "保存录音及转录",
    "Search apps...": "搜索应用...",
    "Search prompts...": "搜索提示词...",
    "Search...": "搜索...",
    "Search prompts": "搜索提示词",
    "Seed Demo Data": "生成演示数据",
    "Select a dictionary JSON file to import.": "选择要导入的词典 JSON 文件。",
    "Select a plugin bundle or ZIP file to install.": "选择要安装的插件包或 ZIP 文件。",
    "Select an extraction provider to start collecting memories.": "选择提取提供商以开始收集记忆。",
    "Select text in any app, press the shortcut, and choose a prompt to process the text.": "在任何应用中选择文本，按快捷键，然后选择提示词处理文本。",
    "Select your preferred microphone:": "选择您偏好的麦克风：",
    "Settings": "设置",
    "Settings...": "设置...",
    "settings.tab.recorder": "录音机",
    "Setup": "设置",
    "Short press to toggle, hold to push-to-talk.": "短按切换，按住按键说话。",
    "Shortcut": "快捷键",
    "Show help:": "显示帮助：",
    "Show in Finder": "在 Finder 中显示",
    "Show menu bar icon": "显示菜单栏图标",
    "Skip Setup": "跳过设置",
    "Snippet": "代码片段",
    "Snippets": "代码片段",
    "Sound": "声音",
    "Speak": "说话",
    "Spoken language": "口语语言",
    "Spoken Language": "口语语言",
    "Spoken feedback": "语音反馈",
    "Start dictation, search history and switch profiles directly from Raycast.": "从 Raycast 直接开始听写、搜索历史和切换配置文件。",
    "Startup": "启动",
    "Step %lld of %lld": "第 %lld 步，共 %lld 步",
    "Stores a WAV recording alongside each transcription. Uses approximately 1 MB per 30 seconds.": "为每个转录存储 WAV 录音。大约每 30 秒使用 1 MB。",
    "Style": "样式",
    "Subdomains are included automatically. E.g. \"google.com\" also matches \"docs.google.com\".": '子域名会自动包含。例如"google.com"也匹配"docs.google.com"。',
    "System Default": "系统默认",
    "System Prompt": "系统提示词",
    "Target": "目标",
    "Target language": "目标语言",
    "Task": "任务",
    "Term": "术语",
    "Term Packs": "术语包",
    "Terms": "术语",
    "Terms are sent to the transcription service for better recognition": "术语会发送到转录服务以提高识别度",
    "Terms help speech recognition identify technical words correctly. Corrections fix common transcription mistakes automatically.": "术语帮助语音识别正确识别技术词汇。纠正自动修复常见转录错误。",
    "Test Microphone": "测试麦克风",
    "Text inserted": "文本已插入",
    "Text replaced": "文本已替换",
    "The file contains no dictionary entries.": "文件不包含词典条目。",
    "The file is not a valid dictionary JSON file.": "文件不是有效的词典 JSON 文件。",
    "The language being spoken. Setting this explicitly improves accuracy.": "正在说的语言。明确设置可提高准确性。",
    "The language change will take effect after restarting DavyWhisper.": "语言更改将在重启 DavyWhisper 后生效。",
    "The notch indicator extends the MacBook notch area to show recording status.": "刘海指示器扩展 MacBook 刘海区域以显示录音状态。",
    "The overlay indicator appears as a floating pill on the screen.": "悬浮指示器显示为屏幕上的浮动胶囊。",
    "This hotkey is also assigned to the %@ slot.": "此快捷键也分配给了 %@ 槽位。",
    "This will permanently delete all stored memories from all plugins. This cannot be undone.": "这将永久删除所有插件中的所有存储记忆。此操作无法撤销。",
    "Time Saved": "节省时间",
    "Timer": "计时器",
    "To use AI prompts, install an LLM provider (e.g. Groq, OpenAI) from the Integrations tab after setup.": "要使用 AI 提示词，请在设置后从集成标签页安装 LLM 提供商（例如 Groq、OpenAI）。",
    "Toggle": "切换",
    "Top": "顶部",
    "Transcribe": "转录",
    "Transcribe All": "全部转录",
    "Transcribe audio:": "转录音频：",
    "Transcribe File...": "转录文件...",
    "Transcribe with language:": "使用语言转录：",
    "Transcription Engine": "转录引擎",
    "Transcription Engines": "转录引擎",
    "Transcriptions shorter than this are skipped for memory extraction.": "短于此长度的转录会被跳过，不进行记忆提取。",
    "Translate to English": "翻译为英语",
    "Translation": "翻译",
    "Trigger": "触发器",
    "Trigger and replacement cannot be empty": "触发器和替换文本不能为空",
    "Try It Out": "试试看",
    "Type": "输入",
    "DavyWhisper": "DavyWhisper",
    "Stable": "稳定版",
    "Stable gets production releases only.": "稳定版仅获取正式发布版本。",
    "DavyWhisper Dev": "DavyWhisper 开发版",
    "DavyWhisper is ready to use in any app.": "DavyWhisper 已在任何应用中准备就绪。",
    "DavyWhisper will start automatically when you log in.": "DavyWhisper 会在您登录时自动启动。",
    "Update Channel": "更新渠道",
    "DavyWhisper works with Raycast. Start dictation and more directly from your launcher.": "DavyWhisper 可与 Raycast 配合使用。从启动器直接开始听写等操作。",
    "Uninstall": "卸载",
    "Uninstall Plugin": "卸载插件",
    "Uninstall %@": "卸载 %@",
    "Unlimited": "无限制",
    "Update": "更新",
    "Update Available": "有可用更新",
    "Updates": "更新",
    "URL Patterns": "URL 模式",
    "Usage Examples": "使用示例",
    "Uses Apple Translate (on-device)": "使用 Apple 翻译（设备端）",
    "Utilities": "实用工具",

    "v%@": "v%@",
    "Version %@ (%@)": "版本 %@ (%@)",
    "Visibility": "可见性",
    "Voice-powered typing for your Mac": "为您的 Mac 提供语音驱动的打字",
    "Waveform": "波形",
    "Welcome to DavyWhisper": "欢迎使用 DavyWhisper",
    "When a prompt is assigned, dictated text will be processed by the LLM before insertion. This replaces translation.": "当分配了提示词后，听写文本会在插入前由 LLM 处理。这会替换翻译功能。",
    "When enabled, transcriptions from this profile are stored as memories and used as context for prompts.": "启用后，此配置文件的转录会被存储为记忆并用作提示词的上下文。",
    "When hidden, the app is accessible via the Dock icon.": "隐藏时，可通过 Dock 图标访问应用。",
    "Words": "词数",
    "Works Offline": "离线可用",
    "Wrong Text": "错误文本",
    "You can access DavyWhisper settings via the Dock icon.": "您可以通过 Dock 图标访问 DavyWhisper 设置。",
    "You can install more engines from the Integrations tab after setup.": "您可以在设置后从集成标签页安装更多引擎。",
    "You have a transcription engine ready.": "您已有一个转录引擎就绪。",
    "You're all set!": "您已准备就绪！",
    "Your activity will appear here after your first transcription.": "您的首次转录后，活动将显示在此处。",
    "Your words appear as text instantly.": "您说的话会立即显示为文本。",

    # Count/format strings
    "%@s - %@s processing": "%1$@s - %2$@s 处理中",
    "%d Prompts": "%d 个提示词",
    "%d Snippets": "%d 个代码片段",
    "%d terms": "%d 个术语",
    "%lld": "%lld",
    "%lld %@": "%1$lld %2$@",
    "%lld %@ (%lld %@)": "%1$lld %2$@ (%3$lld %4$@)",
    "%lld items selected": "%lld 个项目已选中",
    "%lld storage plugin(s) active": "%lld 个存储插件已激活",
    "%lld/%lld": "%1$lld/%2$lld",
    "%@, %@": "%1$@、%2$@",
    "%@, %lld entries": "%1$@、%2$lld 个条目",
    "%@, %lld plugins": "%1$@、%2$lld 个插件",
    "Transcription complete, %lld words": "转录完成，%lld 个词",
    "Playback position": "播放位置",

    # Record row labels
    "Selected": "已选中",
    "Play": "播放",
    "Expanded": "已展开",
    "Collapsed": "已折叠",
    "Remove %@": "移除 %@",
    "Show terms for %@": "显示 %@ 的术语",
    "Settings for %@": "%@ 的设置",
    "Current shortcut: %@. Click to change.": "当前快捷键：%@。点击更改。",
    "Active profile": "活动配置文件",
    "Inserting text": "正在插入文本",
    "Reads back the transcribed text via speech synthesis after each dictation.": "每次听写后通过语音合成朗读转录文本。",
    "Streaming text": "流式文本",
    "© 2024-2026 DavyWhisper Contributors": "© 2024-2026 DavyWhisper 贡献者",
    "Recording Start": "录音开始",
    "Transcription Success": "转录成功",
    "Transcription success": "转录成功",
    "Preview sound": "预览声音",
    "Add custom sound": "添加自定义声音",
    "Choose a sound file": "选择声音文件",
    "You can manage prompts and install more providers in the Prompts and Integrations tabs after setup.": "您可以在设置后在提示词和集成标签页管理提示词并安装更多提供商。",
    "Detect spoken instructions in your dictation (e.g., 'write this as an email') and apply them automatically via LLM.": '检测您听写中的口头指令（例如“写成一封邮件”）并通过 LLM 自动应用。',
    "Inline Commands": "内联命令",
    "All engines installed.": "所有引擎已安装。",
    "App-aware formatting": "应用感知格式化",
    "Automatically format transcribed text based on the target app. Configure the output format per profile.": "根据目标应用自动格式化转录文本。可按配置文件配置输出格式。",
    "Format transcribed text for the target app. Auto-detect chooses the format based on the app's bundle ID. Requires app-aware formatting to be enabled in Recording settings.": "为目标应用格式化转录文本。自动检测根据应用的包标识符选择格式。需要在录音设置中启用应用感知格式化。",
    "Output Format": "输出格式",
    "Output Formatting": "输出格式化",
    "Markdown": "Markdown",
    "AI prompts can rewrite, translate, or summarize.": "AI 提示词可以重写、翻译或总结。",
    "No engines available. Check your internet connection.": "没有可用的引擎。请检查您的网络连接。",
}


def add_chinese_translations(data: dict) -> dict:
    """Add zh-Hans translations to the xcstrings data structure."""
    strings = data.get("strings", {})

    for key, value in strings.items():
        if not isinstance(value, dict):
            continue

        localizations = value.get("localizations", {})

        # Remove German localization
        if "de" in localizations:
            del localizations["de"]

        # Get English value (or key if no English entry)
        en_entry = localizations.get("en", {})
        if isinstance(en_entry, dict):
            en_value = en_entry.get("stringUnit", {}).get("value", key)
        else:
            en_value = key

        # Look up Chinese translation
        zh_value = TRANSLATIONS.get(key)
        if zh_value is None:
            # Try to use the key as-is for format strings or technical strings
            zh_value = en_value

        # Add Chinese localization
        localizations["zh-Hans"] = {
            "stringUnit": {
                "state": "translated",
                "value": zh_value
            }
        }

        value["localizations"] = localizations

    return data


def process_file(input_path: str, output_path: str = None):
    """Process the Localizable.xcstrings file."""
    if output_path is None:
        output_path = input_path

    # Read the input file
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Ensure sourceLanguage is "en"
    data["sourceLanguage"] = "en"

    # Add Chinese translations and remove German
    data = add_chinese_translations(data)

    # Write the output file
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Successfully processed: {output_path}")
    print(f"- Added zh-Hans translations for {len(data.get('strings', {}))} strings")
    print("- Removed German (de) localizations")
    print("- Set sourceLanguage to 'en'")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python translate_localizable.py <path_to_Localizable.xcstrings>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    process_file(input_file, output_file)
